"""empty message

Revision ID: 316f98ba1eca
Revises: b6457fc8d731
Create Date: 2019-05-12 12:08:13.031576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316f98ba1eca'
down_revision = 'b6457fc8d731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'price')
    # ### end Alembic commands ###
