"""empty message

Revision ID: b6457fc8d731
Revises: ea6446e10b5e
Create Date: 2019-05-12 11:42:03.173630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6457fc8d731'
down_revision = 'ea6446e10b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('data', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'data')
    # ### end Alembic commands ###
