"""empty message

Revision ID: f4f2524e5db4
Revises: 316f98ba1eca
Create Date: 2019-05-12 15:50:29.969310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f2524e5db4'
down_revision = '316f98ba1eca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subs', sa.Column('buy_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subs', 'buy_date')
    # ### end Alembic commands ###
